<Project>
  <Target Name="DebugEnsureNodeEnv" BeforeTargets="BuildTsc" Condition=" '$(Configuration)' == 'Debug' AND '$(DesignTimeBuild)' != 'true'">
    <!-- Ensure Node.js is installed -->
    <Exec Command="node --version" ContinueOnError="true" StandardOutputImportance="Low">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
    <Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
  </Target>
</Project>