<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <DisableBuildCompression>true</DisableBuildCompression>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="appsettings.Development.json" />
    <Content Include="appsettings.Development.json" Condition="'$(Configuration)'=='DEBUG'" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="IdGen" />
    <PackageReference Include="IdGen.DependencyInjection" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SqlKata" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.ReDoc" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    <PackageReference Include="System.IO.Hashing" />
    <PackageReference Include="System.Linq.Async" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\WebUI.SourceGenerators\WebUI.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
  </ItemGroup>
</Project>
